spring:
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    hikari:
      schema: books_schema
      connection-ini-sql: CREATE SCHEMA IF NOT EXISTS books_schema
      connection-timeout: 10000

app:
  integration:
    base-url: http://localhost:8082
  cache:
    cache-names:
      - bookByNameAndAuthor
      - bookByCategory
    caches:
      bookByNameAndAuthor:
        expiry: 5m
      bookByCategory:
        expiry: 5m
